version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Four.Dain.10
      MYSQL_DATABASE: cadetApp
      MYSQL_USER: cadet
      MYSQL_PASSWORD: Cadet.80
    ports:
      - "3306:3306"
    volumes:
      - /home/oceance/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: Four.Dain.10
    depends_on:
      - mysql
